name: main

on: push

jobs:
  main:
    name: Build and test
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'Merge branch')"
    steps:
      - run: echo "HELLO WORLD!"